include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # (Performance)
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - unnecessary_const
    - unnecessary_new
    - avoid_unnecessary_containers
    - prefer_final_fields
    - prefer_final_locals
    - avoid_redundant_argument_values

    # (Code Cleanliness)
    - always_declare_return_types
    - use_key_in_widget_constructors
    - sort_child_properties_last
    - sized_box_for_whitespace
    - unnecessary_this
    - prefer_expression_function_bodies
    - prefer_collection_literals
    - prefer_single_quotes

    # (Safety & Error Prevention)
    - annotate_overrides
    - avoid_init_to_null
    - avoid_empty_else
    - avoid_catches_without_on_clauses
    - empty_catches
    - unnecessary_null_checks
    - prefer_typing_uninitialized_variables
    - null_closures
    - avoid_returning_null_for_future

    # (Style & Structure)
    # - require_trailing_commas
    - prefer_final_parameters
    - camel_case_extensions
    - avoid_positional_boolean_parameters
    - no_logic_in_create_state
    - avoid_returning_null
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
